<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ká»‰ yáº¿u ğŸ’–</title>
    <meta content='ká»‰ yáº¿u cá»¥a tá»›ğŸ’' name='description'/>
    <meta content='HTML, nducdtrnducdtr,  hihihihi' name='keywords'/>
    <meta content='nducdtrnducdtr' name='author'/>
    <link href='https://fonts.googleapis.com' rel='preconnect'/>
    <link crossorigin='' href='https://fonts.gstatic.com' rel='preconnect'/>
    <link href='https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;700&amp;display=swap' rel='stylesheet'/>
    <link href='https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;700&amp;display=swap' rel='stylesheet'/>
    <link href='https://fonts.googleapis.com/css2?family=Dancing+Script&amp;display=swap' rel='stylesheet'/>
    <link href='https://i.imgur.com/SgYOQNB.png' rel='icon' type='image/x-icon'/>
    <link rel="stylesheet" href="styles.css">
    <script src='https://cdn.jsdelivr.net/npm/sweetalert2@11.16.0/dist/sweetalert2.all.min.js'></script>
</head>
<body>
<!-- Pháº§n Nháº¡c -->
    <audio class='sembunyi' id='linkmp3' src='nhacphonecert.mp3'></audio>
<!-- Pháº§n áº¢nh Ná»n -->
    <div id='bodyblur'>
        <img id='wallpaper' src='https://i.pinimg.com/1200x/d8/fa/29/d8fa29eb2ec089b407a241512956dd43.jpg' alt='wallpaper'/>
        <div id='beneranblur'></div>
    </div>
<!-- Pháº§n Má»Ÿ QuÃ  Äáº§u -->
    <div id='Content'>
        <div id='suratin' onclick='memulai();'>
            <img src='https://feeldreams.github.io/kadoin.png' alt='Gift'/>
        </div>
        <div id="giftMessage" style="border: 2px solid #fff; border-radius: 15px; padding: 10px; display: flex; background-color: #333; text-align: center; color: #fff; font-family: 'Pacifico', cursive; margin: 20px auto 0 auto; justify-content: center; align-items: center; width: fit-content;">
            <p id='ket' style="margin: 0;">Má»Ÿ  Ä‘i nÃ  !</p>
        </div>       
<!-- Pháº§n Sticker -->
        <div class='kumpulanstiker'>
            <img id='stiker1' src='https://feeldreams.github.io/pusn.gif' alt='Sticker 1'/>
            <img id='stiker2' src='https://feeldreams.github.io/bunga.gif' alt='Sticker 2'/>
            <img id='stiker3' src='https://feeldreams.github.io/mndkat.gif' alt='Sticker 3'/>
            <img id='stiker4' src='https://feeldreams.github.io/smprt.gif' alt='Sticker 4'/>
            <img id='stiker5' src='https://feeldreams.github.io/ngumpet.gif' alt='Sticker 5'/>
            <img id='stiker' onClick='ftaksi();' src='https://feeldreams.github.io/bunga.gif' alt='Sticker'/>
            <img id='stikerAkhir' src='https://feeldreams.github.io/bunga.gif' alt='Sticker Akhir'/>
        </div>
        <p id='halo'>chaÌ€o caÌc baÌ£n thÃ¢n mÃªÌn</p>
<!-- Pháº§n Ná»™i Dung -->
        <div><blockquote id='bq'>
            <p id='kalimat'> caÌc Cáº­uuu Ä‘i chuÌ£p kiÌ‰ yÃªÌu vÆ¡Ìi miÌ€nh nnhaaa ğŸ’•</p>
            <p id='kalimat2'>ngaÌ€y 16/2/2025 tÆ°Ì chuÌ‰ nhÃ¢Ì£t tuÃ¢Ì€n naÌ€y aÌ
                Ä‘iÌ£a chiÌ‰ taÌ£i trÆ°Æ¡Ì€ng THPT ChuÌc ÄÃ´Ì£ng nha
            </p>
            <p id='kalimatbawah'>Ä‘i  nhaaaa</p> 
            <p class='sembunyi' id='kalimatbawah2'> caÌc baÌ£n Ä‘i Ä‘Ã¢Ì€y Ä‘uÌ‰ nha</p> 
            <p class='sembunyi' id='kalimatbawah3'>yÃªu caÌc cáº­u nhiá»uu â¤ï¸</p> 
        </blockquote></div>

<!-- Pháº§n NÃºt Báº¥m -->


        <span class='sembunyi' id='pesanWA'> â¤ï¸â¤ï¸â¤ï¸</span>
    </div>
<!-- Pháº§n Script-->
    <script src="script.js"></script>
</body>
</html>

